### ISSUE TITLE
Pycosat Statistics

### ISSUE THREAD

**Issue by trdavidson** [conda/pycosat#28]
Hey guys,

great binding. I was wondering if it would be possible to include the statistics that are available in the pure C version?

/_------------------------------------------------------------------------_/
/\* Statistics.
 _/
int picosat_variables (PicoSAT *);                      /_ p cnf <m> n _/
int picosat_added_original_clauses (PicoSAT *);         /_ p cnf m <n> _/
size_t picosat_max_bytes_allocated (PicoSAT *);
double picosat_time_stamp (void);                       /_ ... in process _/
void picosat_stats (PicoSAT *);                         /_ > output file _/
unsigned long long picosat_propagations (PicoSAT *);    /_ #propagations _/
unsigned long long picosat_decisions (PicoSAT *);   /_ #decisions _/
unsigned long long picosat_visits (PicoSAT *); /_ #visits */

Thanks!

**Comment by samarthbhargav** [comment]
@trdavidson did you figure out how to get these statistics?

**Comment by Kaleidophon** [comment]
Has there been any progress on this?
