### ISSUE TITLE
picosat.c build error

### ISSUE THREAD

**Issue by ThePrez** [conda/pycosat#35]
picosat.c has `#include <sys/unistd.h>` but on some systems it should just be `#include <unistd.h>`

The build error on IBM i is manifested as:
```
    In file included from pycosat.c:19:0:
    picosat.c:8150:24: fatal error: sys/unistd.h: No such file or directory
     #include <sys/unistd.h>
                            ^
```
To solve my immediate concern, one could simply `#ifdef __PASE__` (defined on IBM i), but I am opening an issue rather than a PR so the project owners can choose their preferred way to address. 

Thanks!

**Comment by dholth** [comment]
I was able to include just `unistd.h` on osx

```
#include <unistd.h>

int main(int argc, char **argv) {
    return 0;
}
```

**Comment by danmilon** [comment]
This issue prevents pycosat from being compiled with musl libc that is commonly found in alpine-based systems.
